(function () {
  window.SAFFRON_DEFAULT_MENU_ITEMS = [
    {
      id: "101",
      name: "Truffle Angus Burger",
      category: "burgers",
      price: 18,
      image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80",
      description: "Char-grilled beef, cheddar, onion jam, truffle aioli, and toasted brioche.",
      rating: "4.9",
      badge: "Best Seller",
      meta: "Gourmet Burger",
      icon: "fa-burger",
      halal: true,
      available: true
    },
    {
      id: "102",
      name: "Saffron Smash Burger",
      category: "burgers",
      price: 16,
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80",
      description: "Double smash patties, house sauce, pickles, cheddar, and soft potato bun.",
      rating: "4.8",
      badge: "Popular",
      meta: "House Favorite",
      icon: "fa-fire",
      halal: true,
      available: true
    },
    {
      id: "103",
      name: "Flamehouse Pepperoni Pizza",
      category: "pizza",
      price: 21,
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80",
      description: "Roasted pepperoni, fior di latte, tomato base, and basil oil finish.",
      rating: "4.8",
      badge: "Stone Baked",
      meta: "Signature Pizza",
      icon: "fa-pizza-slice",
      halal: true,
      available: true
    },
    {
      id: "104",
      name: "Black Truffle Burrata Pizza",
      category: "pizza",
      price: 24,
      image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=1200&q=80",
      description: "Burrata, truffle oil, wild mushrooms, cracked pepper, and slow-risen crust.",
      rating: "4.9",
      badge: "Luxury Pick",
      meta: "Premium Selection",
      icon: "fa-crown",
      halal: true,
      available: true
    },
    {
      id: "105",
      name: "Smoked Saffron Platter",
      category: "bbq",
      price: 29,
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
      description: "Mixed grilled meats, saffron rice, roasted vegetables, and signature sauce trio.",
      rating: "5.0",
      badge: "Chef Choice",
      meta: "Signature Grill",
      icon: "fa-fire-flame-curved",
      halal: true,
      available: true
    },
    {
      id: "106",
      name: "Royal BBQ Ribs",
      category: "bbq",
      price: 27,
      image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80",
      description: "Slow-glazed ribs with herb fries, black pepper jus, and charred lemon.",
      rating: "4.9",
      badge: "Grill Special",
      meta: "Slow Cooked",
      icon: "fa-drumstick-bite",
      halal: true,
      available: true
    },
    {
      id: "107",
      name: "Citrus Spark Mocktail",
      category: "drinks",
      price: 8,
      image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1200&q=80",
      description: "Fresh lime, orange infusion, mint, and sparkling finish over crystal ice.",
      rating: "4.7",
      badge: "Refreshing",
      meta: "Fresh Beverage",
      icon: "fa-glass-water",
      halal: true,
      available: true
    },
    {
      id: "108",
      name: "Rose Saffron Cooler",
      category: "drinks",
      price: 9,
      image: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=1200&q=80",
      description: "Rose essence, saffron infusion, chilled citrus, and mint with floral finish.",
      rating: "4.8",
      badge: "House Drink",
      meta: "Signature Drink",
      icon: "fa-snowflake",
      halal: true,
      available: true
    },
    {
      id: "109",
      name: "Molten Date Cake",
      category: "desserts",
      price: 11,
      image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=80",
      description: "Warm date sponge with caramel center, vanilla cream, and pistachio dust.",
      rating: "4.8",
      badge: "Sweet Finale",
      meta: "Dessert Favorite",
      icon: "fa-cake-candles",
      halal: true,
      available: true
    },
    {
      id: "110",
      name: "Pistachio Kunafa Cream Cup",
      category: "desserts",
      price: 12,
      image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80",
      description: "Crisp kunafa layers, whipped cream, pistachio crumble, and fragrant syrup.",
      rating: "4.9",
      badge: "Luxury Dessert",
      meta: "Crowd Favorite",
      icon: "fa-heart",
      halal: true,
      available: true
    },
    {
      id: "111",
      name: "Charcoal Chicken Supreme",
      category: "bbq",
      price: 23,
      image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1200&q=80",
      description: "Half grilled chicken with saffron butter glaze, fragrant rice, and fresh herbs.",
      rating: "4.8",
      badge: "Grill Master",
      meta: "Charcoal Grill",
      icon: "fa-fire",
      halal: true,
      available: true
    },
    {
      id: "112",
      name: "Noir Crispy Chicken Burger",
      category: "burgers",
      price: 17,
      image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=1200&q=80",
      description: "Golden fried chicken, slaw, chili mayo, and glossy toasted bun.",
      rating: "4.7",
      badge: "Crispy Favorite",
      meta: "Crispy Classic",
      icon: "fa-burger",
      halal: true,
      available: true
    }
  ];
})();
